#! Read ReadMe.txt first, if you have not already done so!

##########################################################################
# Function to create artificial data with known kernel.
# Code that calls this function and creates a data set 
# begins at line 82 of this script. 
##########################################################################
createTestData <- function(doSpp,type,dataGenNumber,home,dataDir) {

oldwd = getwd(); 

if(type=="Gaussian") {alpha=0.01; cur_dist_wts <- gaukernel}   
if(type=="Exponential") {alpha=0.3; cur_dist_wts <- expkernel}
if(type=="Sigmoid"){alpha=13; cur_dist_wts <- stepkernel} 
if(type=="Lines") {alpha=c(0.35,0.33,-0.4); cur_dist_wts = linekernel} 

pde.target = ifelse(doSpp=="PSSP",0.165,0.1); 

########################################################## 
### Read in the data 
##########################################################
outS=loadSurvivalData(dataDir,doSpp); 
D.s=outS$D; # data on survival and covariates 
sppData.s=outS$sppData; # annulus data only 
nonCompLength.s=outS$nonCompLength.s

outG=loadGrowthData(dataDir,doSpp); 
D.g=outG$D; # data on growth and covariates 
sppData.g=outG$sppData; # annulus data only 
nonCompLength.g=outG$nonCompLength.g

################################################################# 
# Fit models with assumed kernel 
#################################################################
midRings <- c(seq(1,19,2),seq(22.5,47.5,5),seq(55,145,10)); 
dist.wts=cur_dist_wts(x=midRings,alpha=alpha) ;
W.s=sppData.s%*%c(rep(0,nonCompLength.s),dist.wts)
fitS=glm(survives ~ W.s + Group + logarea,  data=D.s, family=binomial)    
W.g=sppData.g%*%c(rep(0,nonCompLength.g),dist.wts)
fitG=lm(logarea.t1 ~ W.g + Group + logarea.t0, data=D.g)

##################################################################
# How important is competition? 
##################################################################
fitS0=glm(survives ~ Group + logarea, data=D.s, family=binomial)    
fitG0=lm(logarea.t1 ~ Group + logarea.t0, data=D.g)
pde.G = PVE(fitG0,fitG);
pde.S = PDE(fitS0,fitS);

################################################################# 
# Create and save artificial data generated by the fitted models
#################################################################

D.g$logarea.t1=fitG$fitted.values + sample(fitG$residuals,replace=TRUE)
sppData.g[,which(colnames(sppData.g)=="logarea.t1")]=D.g$logarea.t1

bonus.Ws=uniroot(findBonusWs,interval=c(-0.5,1),pde.target=pde.target,D.s=D.s,W.s=W.s,nreps=10)$root;  

pde.S.fake <- 0
while(pde.S.fake < 0.9*pde.target) {
 D.s <- addBonusWs(bonus.Ws,D.s,W.s)
 fitS.fake=glm(survives ~ W.s + Group + logarea, data=D.s, family=binomial)    
 fitS0.fake=glm(survives ~ Group + logarea, data=D.s, family=binomial)   
 pde.S.fake = PDE(fitS0.fake,fitS.fake);
}
sppData.s[,which(colnames(sppData.s)=="survives")]=D.s$survives

README <- paste(doSpp," Fake data ", type, " kernel, no year effect, bonus.Ws: ",
                as.character(bonus.Ws),sep="")
setwd(home); 
dirName=sprintf("ArtData%s",dataGenNumber)
unlink(dirName,recursive=TRUE)
dir.create(dirName)
setwd(dirName)
save(file=sprintf("ArtData%s.Rdata",dataGenNumber),
     list=c("D.s","D.g","sppData.s","sppData.g","README","alpha","doSpp","nonCompLength.s","nonCompLength.g",
            "bonus.Ws","cur_dist_wts","pde.G","pde.S","pde.S.fake"))             
setwd(oldwd);

return(pde.S.fake); 
}

##################################################################################### 
# Create a collection of artificial data sets 
#####################################################################################
setwd("c:/repos/drivers/Manuscripts/Sheffield/Rcode/Competition")  #CHANGE ME 
 
home=paste(getwd(),"/",sep=""); dataDir=home; 
source("LoadData.R"); source("DistanceKernelSubs.R"); 

# key: 1xx = ARTR, 2xx=PSSP; x1x = Exponential; x2x = Gaussian; x3x=Lines; x4x=Sigmoid 
for(k in 1:1) {
doSpp="ARTR"
out = createTestData(doSpp="ARTR",type="Exponential",dataGenNumber=100+k,home=home,dataDir=dataDir)	
cat(out,"\n")
out = createTestData(doSpp="ARTR",type="Gaussian",dataGenNumber=110+k,home=home,dataDir=dataDir)
cat(out,"\n")
out = createTestData(doSpp="ARTR",type="Lines",dataGenNumber=120+k,home=home,dataDir=dataDir)
cat(out,"\n")
out = createTestData(doSpp="ARTR",type="Sigmoid",dataGenNumber=130+k,home=home,dataDir=dataDir)
cat(out,"\n")
}

for(k in 1:1) {
doSpp="PSSP"
out = createTestData(doSpp="PSSP",type="Exponential",dataGenNumber=200+k,home=home,dataDir=dataDir)	
cat(out,"\n")
out = createTestData(doSpp="PSSP",type="Gaussian",dataGenNumber=210+k,home=home,dataDir=dataDir)
cat(out,"\n")
out = createTestData(doSpp="PSSP",type="Lines",dataGenNumber=220+k,home=home,dataDir=dataDir)
cat(out,"\n")
out = createTestData(doSpp="PSSP",type="Sigmoid",dataGenNumber=230+k,home=home,dataDir=dataDir)
cat(out,"\n")
}
